import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/header'
import Masthead from '../components/masthead'
import About from '../components/about'
import shortmoon from "../public/assets/back.png";
import Work from '../components/work'

const Home: NextPage = () => {
  return (
    <div className="background">
      
      <Head>
        <title>Portfolio Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header/>
      <Masthead/>
      <About/>
      <Work/>
    </div>
  )
}

export default Home
